version: '3.8'

services:
  ndot-postgres:
    image: postgres:15-alpine
    container_name: ndot-postgres
    environment:
      POSTGRES_DB: ndot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5