DROP TABLE IF EXISTS snmpv3_parameters;
DROP TABLE IF EXISTS snmpv2_parameters;
DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS snmp_template;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;