// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateDevice(ctx context.Context, arg CreateDeviceParams) error
	DeleteDevice(ctx context.Context, deviceID int32) error
	GetDeviceById(ctx context.Context, deviceID int32) (Device, error)
	GetDeviceByIp(ctx context.Context, ip string) (Device, error)
	ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error)
	UpdateDeviceIP(ctx context.Context, arg UpdateDeviceIPParams) error
	UpdateDeviceManufacturer(ctx context.Context, arg UpdateDeviceManufacturerParams) error
	UpdateDeviceModel(ctx context.Context, arg UpdateDeviceModelParams) error
	UpdateDeviceName(ctx context.Context, arg UpdateDeviceNameParams) error
	UpdateDeviceType(ctx context.Context, arg UpdateDeviceTypeParams) error
}

var _ Querier = (*Queries)(nil)
